Adding web notifications and Modal Component
Training-Sena/RockolaAppKoombea pull request #22
Opened 2018-11-09 20:27 UTC by Llerena97

2018-11-20 15:07 UTC, lmsilvera requested changes

2018-11-20 15:07 UTC, lmsilvera commented on app/javascript/components/login.vue
> +  </form>
por qué si el PR es de web notifications haces cambios en login form?

2018-11-20 15:07 UTC, lmsilvera commented on app/javascript/packs/application.js
> +    console.log('Recibido')
```suggestion
```

2018-11-20 15:07 UTC, lmsilvera commented on app/views/layouts/application.html.erb
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
por qué añades las librerias de esta manera? no es mejor con el package json o con una gema de rails?

2018-11-20 20:35 UTC, Llerena97 commented on app/javascript/components/login.vue
> +  </form>
Es un refactor de los features y solucionando los bugs que vienen de QA

2018-11-20 20:37 UTC, Kevindm14 commented on app/javascript/packs/application.js
> +    console.log('Recibido')
Done

2018-11-20 20:37 UTC, Kevindm14 commented on app/views/layouts/application.html.erb
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
Done

2018-11-21 19:53 UTC, lmsilvera requested changes

2018-11-21 19:53 UTC, lmsilvera commented on app/javascript/components/confirmation-modal.vue
> +	  <p>Êtes-vous certain de vouloir supprimer l'utilisateur <strong>{{ user.name }}</strong> ?</p>
¿este mensaje para qué es?

2018-11-21 19:53 UTC, lmsilvera commented on app/javascript/components/confirmation-modal.vue
> +		 <button class="cancel" @click="onCancel">Annuler</button>
¿qué idioma es ese?

2018-11-21 19:53 UTC, lmsilvera commented on app/javascript/components/confirmation-modal.vue
> +}
por favor corregir las tabulaciones

2018-11-21 19:53 UTC, lmsilvera commented on app/javascript/components/confirmation-modal.vue
> +<style>
el CSS creo que deberia ir a los archivos de `stylesheets`

2018-11-21 20:04 UTC, merged